name: Update EuroJackpot Stats

on:
  schedule:
    - cron: '0 12 * * 6'  # Run every Saturday at 12:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run EuroJackpot stats script
        run: python eurojackpot_export.py
        
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update EuroJackpot stats
          file_pattern: results.json
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: SlashGordon/howtolosemoneyfast_web
          event-type: eurojackpot-updated